CREATE SCHEMA B97452_PROYECTO2_IF4101;
USE B97452_PROYECTO2_IF4101;

CREATE TABLE B97452_PROYECTO2_IF4101.tb_ROLE
(
	 ID        INT PRIMARY KEY 
    ,TYPE      VARCHAR(36) NOT NULL
);

-------------------------------------

INSERT INTO b97452_proyecto2_if4101.tb_role(ID, TYPE)VALUES(1,'Admin'),(2,'Customer');

------------------------------------

CREATE TABLE B97452_PROYECTO2_IF4101.tb_USERS
(
	 ID        INT AUTO_INCREMENT PRIMARY KEY
    ,USER_NAME VARCHAR(36) NOT NULL UNIQUE
    ,PASSWORD  VARCHAR(36) NOT NULL
    ,ID_ROLE   INT 
    ,CONSTRAINT FK_USER_ROLE FOREIGN KEY (ID_ROLE) REFERENCES B97452_PROYECTO2_IF4101.tb_ROLE (ID)
);

-----------------------------------

INSERT INTO b97452_proyecto2_if4101.tb_users(USER_NAME, PASSWORD, ID_ROLE)VALUES('admin', 'superuser', 1);

-----------------------------------

DELIMITER $$
CREATE PROCEDURE b97452_proyecto2_if4101.sp_VALIDATE_USER
(
IN param_USER_NAME VARCHAR(36), 
IN param_PASSWORD VARCHAR(36),
OUT out_RETURN    INT)
BEGIN 
	IF NOT EXISTS (SELECT USER_NAME FROM b97452_proyecto2_if4101.tb_users WHERE USER_NAME = param_USER_NAME) THEN
		SELECT -1 INTO out_RETURN;
	ELSE 
		IF(1 = (SELECT ID_ROLE FROM b97452_proyecto2_if4101.tb_users WHERE USER_NAME = param_USER_NAME AND PASSWORD = param_PASSWORD)) THEN
			SELECT 1 INTO out_RETURN;
		ELSEIF(2 = (SELECT ID_ROLE FROM b97452_proyecto2_if4101.tb_users WHERE USER_NAME = param_USER_NAME AND PASSWORD = param_PASSWORD)) THEN
			SELECT 2 INTO out_RETURN;
        END IF;
	END IF;
END;

-----------------------------------

DELIMITER $$
CREATE PROCEDURE b97452_proyecto2_if4101.sp_REGISTER_ADMIN
(
IN param_USER_NAME VARCHAR(36), 
IN param_PASSWORD VARCHAR(36),
OUT out_RETURN    INT)
BEGIN 
	IF EXISTS (SELECT USER_NAME FROM b97452_proyecto2_if4101.tb_users WHERE USER_NAME = param_USER_NAME AND PASSWORD = param_PASSWORD) THEN
		SELECT 0 INTO out_RETURN;
	ELSE 
		INSERT INTO b97452_proyecto2_if4101.tb_users(USER_NAME, PASSWORD, ID_ROLE)
        VALUES(param_USER_NAME, param_PASSWORD, 1);
        SELECT 1 INTO out_RETURN;
	END IF;
END;

-----------------------------------

CREATE TABLE B97452_PROYECTO2_IF4101.tb_CATEGORY
(
	 ID   INT AUTO_INCREMENT PRIMARY KEY
	,TYPE VARCHAR(42) NOT NULL	
);

-----------------------------------

INSERT INTO B97452_PROYECTO2_IF4101.tb_CATEGORY(TYPE)VALUES('Cleaning products')

-----------------------------------

DELIMITER $$
CREATE PROCEDURE b97452_proyecto2_if4101.sp_GET_ALL_CATEGORIES()
BEGIN
	SELECT ID, TYPE FROM b97452_proyecto2_if4101.tb_category;
END;

-----------------------------------

CREATE TABLE B97452_PROYECTO2_IF4101.tb_IMAGE
(
	 ID         INT AUTO_INCREMENT PRIMARY KEY
    ,IMAGE_NAME VARCHAR(52) NOT NULL
);

-----------------------------------

CREATE TABLE B97452_PROYECTO2_IF4101.tb_PRODUCTS
(
	 ID          INT AUTO_INCREMENT PRIMARY KEY
    ,NAME        VARCHAR(36) NOT NULL UNIQUE
    ,PRICE       DECIMAL(9, 2) NOT NULL
    ,DESCRIPTION VARCHAR(50) NULL 
	,ID_CATEGORY INT NOT NULL
    ,ID_IMAGE    INT NOT NULL
    ,CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES B97452_PROYECTO2_IF4101.tb_CATEGORY (ID)
    ,CONSTRAINT FK_PRODUCTS_IMAGE FOREIGN KEY (ID_IMAGE) REFERENCES B97452_PROYECTO2_IF4101.tb_IMAGE (ID)
);

-----------------------------------

DELIMITER $$
CREATE PROCEDURE b97452_proyecto2_if4101.sp_REGISTER_PRODUCT
(
IN param_NAME        VARCHAR(36), 
IN param_PRICE       DECIMAL(9, 2),
IN param_DESCRIPTION VARCHAR(50),
IN param_CATEGORY	 VARCHAR(36),		
IN param_IMAGE		 VARCHAR(52),
OUT out_RETURN       INT)
BEGIN
	DECLARE local_CATEGORY_ID INT;
    DECLARE local_IMAGE_ID    INT;
	IF EXISTS (SELECT NAME FROM b97452_proyecto2_if4101.sp_REGISTER_PRODUCT WHERE NAME = param_NAME) THEN
		SELECT 0 INTO out_RETURN;
	ELSE 
		INSERT INTO B97452_PROYECTO2_IF4101.tb_IMAGE(IMAGE_NAME)VALUES(param_IMAGE);
        
		SET local_IMAGE_ID = (SELECT LAST_INSERT_ID());
		SET local_CATEGORY_ID = (SELECT ID FROM B97452_PROYECTO2_IF4101.tb_CATEGORY WHERE TYPE = param_CATEGORY);
        
		INSERT INTO b97452_proyecto2_if4101.sp_REGISTER_PRODUCT(NAME, PRICE, DESCRIPTION, ID_CATEGORY, ID_IMAGE)
        VALUES(param_NAME, param_PRICE, param_DESCRIPTION, local_CATEGORY_ID, local_IMAGE_ID);
        SELECT 1 INTO out_RETURN;
	END IF;
END;